name: Update Publications and Deploy

on:
  schedule:
    - cron: "0 5 * * 1"
  workflow_dispatch:
  
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
permissions:
  contents: write
  pages: write
  id-token: write


jobs:
  update-publications:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - run: pip install requests

      - name: Update publication CSV
        run: python update_publications_from_orcid.py

      - name: Commit updated CSV
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update PublicationList_vCSV.csv"
          file_pattern: csv/PublicationList_vCSV.csv

  build-pages:
    needs: update-publications
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Build GitHub Pages content
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site

  deploy-pages:
    needs: build-pages
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4